version: 1
disable_existing_loggers: False
formatters:
  timestamped:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: timestamped
    filename: requests.txt
    maxBytes: 5000
root:
  level: INFO
  handlers: [console]